# -*- coding: utf-8 -*-
"""Task2_version1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kamjdakAFWSiSie2Sxo1LV1DNVqmvnwr
"""

import cartopy

import xarray as xr
import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

# Load the dataset
ds = xr.open_dataset('MAIAC_AOD_2024.nc')

ds.head()

print(ds.data_vars)

# Extract variables
lon = ds.lon.values
lat = ds.lat.values
aod = ds.AOD.values

# Create the figure and map projection
fig = plt.figure(figsize=(12, 10))
ax = plt.axes(projection=ccrs.PlateCarree())

# Add geographic features for Texas
ax.add_feature(cfeature.STATES.with_scale('10m'), edgecolor='black')
ax.add_feature(cfeature.COASTLINE)
ax.set_extent([-107, -93, 25, 37]) # Zoom in on Texas coordinates

# Create the contour map
#contour = ax.contourf(lon, lat, aod, levels=20, vmin=0, vmax=0.5, cmap='viridis', transform=ccrs.PlateCarree())
# This forces the color steps to happen every 0.05 units between 0 and 0.5
my_levels = np.linspace(0, 0.5, 21)
contour = ax.contourf(lon, lat, aod, levels=my_levels, cmap='viridis', extend='max')
# Add colorbar and labels
cbar = plt.colorbar(contour, ax=ax, orientation='vertical', pad=0.02, aspect=20)
cbar.set_label('AOD Level')
plt.title('Texas MAIAC AOD Contour Map (2024)')
# Save the map
plt.savefig('Texas_AOD_Contour_image.png', dpi=300, bbox_inches='tight')
print("Map saved as Texas_AOD_Contour_image.png")